version: '2'
volumes:
  db_data: {}
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_USER=fs_user
      - MYSQL_PASSWORD=fs_pass
      - MYSQL_DATABASE=facturascripts
  app:
    image: dibanez/facturascripts
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    links:
      - db
    environment:
      - MYSQL_SERVER=db
      - MYSQL_PASSWORD=fs_pass
      - MYSQL_USER=fs_user